version: "3"

services:
  server:
    build: ./server/
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/server:rw
    command: npm start

  app:
    build: ./app/
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app:rw
    command: npm start
